"""质控标记常量。

QC_FLAG   : 自动删除原因（非空即为程序建议删除，可在界面中恢复）。
REVIEW    : 低置信异常标记，保留记录并进入人工检查清单。
"""

# ---- 自动删除 ----
DELETE_INVALID_BASIC_FIELD = "DELETE_INVALID_BASIC_FIELD"
DELETE_SHIP = "DELETE_SHIP"
DELETE_MASKSTID = "DELETE_MASKSTID"
DELETE_DEEP_LAND = "DELETE_DEEP_LAND"
DELETE_SAME_TIME_OFF_TRAJECTORY = "DELETE_SAME_TIME_OFF_TRAJECTORY"
DELETE_HIGH_CONFIDENCE_ISOLATED_SPIKE = "DELETE_HIGH_CONFIDENCE_ISOLATED_SPIKE"
DELETE_STRICT_DUPLICATE = "DELETE_STRICT_DUPLICATE"
DELETE_STATION_YEAR_LT_MIN = "DELETE_STATION_YEAR_LT_MIN"

# ---- 镜像修复建议（人工确认后才生效）----
MIRROR_FIX_SUGGESTED = "MIRROR_FIX_SUGGESTED"
FIX_MIRROR_LON = "MIRROR_LON"
FIX_MIRROR_LAT = "MIRROR_LAT"
FIX_MIRROR_BOTH = "MIRROR_BOTH"

# ---- 人工检查 ----
SAME_TIME_DISTANT_POSITIONS = "SAME_TIME_DISTANT_POSITIONS"
COORDINATE_0_0 = "COORDINATE_0_0"
SUDDEN_ZERO_AND_RETURN = "SUDDEN_ZERO_AND_RETURN"
SERIES_SPIKE = "VALUE_SERIES_SPIKE"
SERIES_STEP = "VALUE_SERIES_STEP"

# ---- 人工决定 ----
MANUAL_DELETE = "MANUAL_DELETE"
MANUAL_KEEP = "MANUAL_KEEP"
MANUAL_REPAIR = "MANUAL_REPAIR"

AUTO_DELETE_FLAGS = (
    DELETE_INVALID_BASIC_FIELD,
    DELETE_SHIP,
    DELETE_MASKSTID,
    DELETE_DEEP_LAND,
    DELETE_SAME_TIME_OFF_TRAJECTORY,
    DELETE_HIGH_CONFIDENCE_ISOLATED_SPIKE,
    DELETE_STRICT_DUPLICATE,
    DELETE_STATION_YEAR_LT_MIN,
)

REVIEW_FLAGS = (
    MIRROR_FIX_SUGGESTED,
    SAME_TIME_DISTANT_POSITIONS,
    COORDINATE_0_0,
    SUDDEN_ZERO_AND_RETURN,
    SERIES_SPIKE,
    SERIES_STEP,
)
